name: 'call sha in other file'
jobs:
  check-other-file:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Call sha in other file
        run: echo "prueba.yml call in  other file"
